find_path(HELLO_INCLUDE_DIR hello.h /home/kiki/github/qt/cmake-demo/t3/lib)
find_library(HELLO_LIBRARY hello /home/kiki/github/qt/cmake-demo/t3/cbuild/lib)
if(HELLO_INCLUDE_DIR AND HELLO_LIBRARY)
    set(HELLO_FOUND TRUE)
endif()
if(HELLO_FOUND)
    if(NOT HELLO_FIND_QUIETLY)
        message(STATUS "Found hello: ${HELLO_LIBRARY}")
    endif()
else()
    if(HELLO_FIND_REQUIRED)
        message(FATAL_ERROR "Could not find hello library")
    endif()
endif()